apiVersion: v1
kind: Pod
metadata:
  name: nginxwebserver
  labels:
    name: nginxwebserver
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"